<?php

namespace App\Filament\Resources\Applicants\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ApplicantInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('period.name')
                    ->label(__('filament.labels.period'))
                    ->placeholder('-'),
                TextEntry::make('code')
                    ->label(__('filament.labels.code'))
                    ->placeholder('-'),
                TextEntry::make('code_cepre')
                    ->label(__('filament.labels.code_cepre'))
                    ->placeholder('-'),
                TextEntry::make('paternal_surname')
                    ->label(__('filament.labels.paternal_surname'))
                    ->placeholder('-'),
                TextEntry::make('maternal_surname')
                    ->label(__('filament.labels.maternal_surname'))
                    ->placeholder('-'),
                TextEntry::make('names')
                    ->label(__('filament.labels.names'))
                    ->placeholder('-'),
                TextEntry::make('documentType.name')
                    ->label(__('filament.labels.document_type'))
                    ->placeholder('-'),
                TextEntry::make('document_number')
                    ->label(__('filament.labels.document_number'))
                    ->placeholder('-'),
                TextEntry::make('email')
                    ->label(__('filament.labels.email_address'))
                    ->placeholder('-'),
                TextEntry::make('size')
                    ->label(__('filament.labels.size'))
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('weight')
                    ->label(__('filament.labels.weight'))
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('gender.name')
                    ->label(__('filament.labels.gender'))
                    ->placeholder('-'),
                TextEntry::make('cellular_phone')
                    ->label(__('filament.labels.cellular_phone'))
                    ->placeholder('-'),
                TextEntry::make('phone')
                    ->label(__('filament.labels.phone'))
                    ->placeholder('-'),
                TextEntry::make('other_phone')
                    ->label(__('filament.labels.other_phone'))
                    ->placeholder('-'),
                TextEntry::make('ubigeo.id')
                    ->label(__('filament.labels.ubigeo'))
                    ->placeholder('-'),
                TextEntry::make('direction')
                    ->label(__('filament.labels.direction'))
                    ->placeholder('-'),
                TextEntry::make('school.id')
                    ->label(__('filament.labels.school')),
                TextEntry::make('university.name')
                    ->label(__('filament.labels.university'))
                    ->placeholder('-'),
                TextEntry::make('site.name')
                    ->label(__('filament.labels.site'))
                    ->placeholder('-'),
                TextEntry::make('start_study')
                    ->label(__('filament.labels.start_study'))
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('end_study')
                    ->label(__('filament.labels.end_study'))
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('date_birth')
                    ->label(__('filament.labels.date_birth'))
                    ->date()
                    ->placeholder('-'),
                TextEntry::make('countryBirth.name')
                    ->label(__('filament.labels.country_birth'))
                    ->placeholder('-'),
                TextEntry::make('ubigeo_birth_id')
                    ->label(__('filament.labels.ubigeo_birth_id'))
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('modality1.name')
                    ->label(__('filament.labels.modality1'))
                    ->placeholder('-'),
                TextEntry::make('modality2.name')
                    ->label(__('filament.labels.modality2'))
                    ->placeholder('-'),
                TextEntry::make('speciality1.name')
                    ->label(__('filament.labels.speciality1'))
                    ->placeholder('-'),
                TextEntry::make('speciality2.name')
                    ->label(__('filament.labels.speciality2'))
                    ->placeholder('-'),
                TextEntry::make('speciality3.name')
                    ->label(__('filament.labels.speciality3'))
                    ->placeholder('-'),
                TextEntry::make('speciality4.name')
                    ->label(__('filament.labels.speciality4'))
                    ->placeholder('-'),
                TextEntry::make('speciality5.name')
                    ->label(__('filament.labels.speciality5'))
                    ->placeholder('-'),
                TextEntry::make('speciality6.name')
                    ->label(__('filament.labels.speciality6'))
                    ->placeholder('-'),
                TextEntry::make('classroom1_id')
                    ->label(__('filament.labels.classroom1'))
                    ->placeholder('-'),
                TextEntry::make('classroom2_id')
                    ->label(__('filament.labels.classroom2'))
                    ->placeholder('-'),
                TextEntry::make('classroom3_id')
                    ->label(__('filament.labels.classroom3'))
                    ->placeholder('-'),
                TextEntry::make('classroom_voca_id')
                    ->label(__('filament.labels.classroom_voca'))
                    ->placeholder('-'),
                IconEntry::make('annulled')
                    ->label(__('filament.labels.annulled'))
                    ->boolean(),
                TextEntry::make('user.name')
                    ->label(__('filament.labels.user')),
                TextEntry::make('created_at')
                    ->label(__('filament.labels.created_at'))
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->label(__('filament.labels.updated_at'))
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
